import React, { useCallback, useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { api, errorMessage, setCsrf } from './api.js'
import { date, label, mergeEvents, normalizeModelSelection, promptDifference, safeMessage, type ModelSelection, type SessionEvent } from './model.js'
import './styles.css'

type Page = 'overview' | 'models' | 'sessions' | 'memory' | 'prompts' | 'heartbeat' | 'schedules' | 'diagnostics' | 'extensions'
const pages: Array<[Page, string, string]> = [['overview', '运行总览', '01'], ['models', '模型设置', '02'], ['sessions', '会话', '03'], ['memory', '长期记忆', '04'], ['prompts', '系统提示词', '05'], ['heartbeat', 'Heartbeat', '06'], ['schedules', '定时任务', '07'], ['diagnostics', '诊断记录', '08'], ['extensions', 'Skills 与提案', '09']]
interface Status { lifecycle: string; qq: string; startedAt: string; model: { provider: string; model: string } | null; lastInteraction: string | null; tasks: Array<{ sessionId: string; turn: number; startedAt: string }>; pending: { memory: number; outbound: number }; recent: Record<string, unknown>[]; foregroundSessionId: string; heartbeat: HeartbeatView }
interface Job { id: string; role: string; status: string; startedAt: string; endedAt?: string; result?: { status?: string; action?: { type?: string }; policy?: { code?: string } }; error?: string }
interface HeartbeatSettings { policy: { timeZone: string; quietHours: { start: string; end: string }; cooldownMinutes: number; maxContactsPerDay: number }; foregroundMs: number; backgroundMs: number; foregroundPaused: boolean; backgroundPaused: boolean }
interface HeartbeatView { settings: HeartbeatSettings; revision: string; next: { foreground: string | null; background: string | null }; jobs: Job[] }
interface MemoryDoc { path: string; hash: string; metadata: { summary: string; category: string; importance: string; frequency: string; sources: string[]; updatedAt?: string }; content: string }
interface PromptDoc { text: string; hash: string }
interface PromptView { soul: PromptDoc; mission: PromptDoc; history: Array<{ key: string; at: string; before: PromptDoc; after: PromptDoc }>; active: Record<string, { soulHash: string; missionHash: string }>; internal: Record<string, string> }
interface ModelSettingsView { selection: ModelSelection; revision: number; configPath: string | null; applies: 'live' | 'restart' }

function useResource<T>(path: string, revision: number) {
  const [data, setData] = useState<T>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => {
    const controller = new AbortController(); setLoading(true)
    void api<T>(path, 'GET', undefined, controller.signal).then(value => { setData(value); setError('') }).catch(error => { if (!controller.signal.aborted) setError(errorMessage(error)) }).finally(() => { if (!controller.signal.aborted) setLoading(false) })
    return () => controller.abort()
  }, [path, revision])
  return { data, error, loading }
}
function Notice({ children, good = false }: { children?: React.ReactNode; good?: boolean }) { return children ? <div className={`notice ${good ? 'good' : ''}`} role="status">{children}</div> : null }
function Empty({ children = '暂无记录' }: { children?: React.ReactNode }) { return <div className="empty">{children}</div> }
function Badge({ value }: { value: unknown }) { return <span className={`badge ${['ready', 'running', 'completed'].includes(String(value)) ? 'success' : ['failed', 'error'].includes(String(value)) ? 'danger' : ''}`}>{label(value)}</span> }
function Json({ value }: { value: unknown }) { return <pre className="json">{JSON.stringify(value, null, 2)}</pre> }
function Login({ onLogin }: { onLogin: () => void }) {
  const [token, setToken] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  return <main className="login"><div className="login-brand"><span className="brand-symbol">P</span><span>PERSONAL GROWTH</span></div><section className="login-form"><div className="eyebrow">LOCAL ADMINISTRATION</div><h1>管理台</h1><form onSubmit={event => { event.preventDefault(); setBusy(true); void api<{ csrfToken: string }>('login', 'POST', { token }).then(value => { setCsrf(value.csrfToken); setToken(''); onLogin() }).catch(error => setError(errorMessage(error))).finally(() => setBusy(false)) }}><label>访问 Token<input autoFocus type="password" autoComplete="off" required value={token} onChange={event => setToken(event.target.value)} /></label><Notice>{error}</Notice><button className="primary wide" disabled={busy}>{busy ? '正在验证…' : '登录'}</button></form><div className="login-footer">127.0.0.1 · 私有实例</div></section></main>
}
function Overview({ data }: { data?: Status }) {
  if (!data) return <Empty>正在读取运行状态…</Empty>
  return <><div className="section-heading"><h2>当前运行</h2><span className="muted">启动于 {date(data.startedAt)}</span></div><div className="metrics">{[['Host', data.lifecycle], ['QQ 通道', data.qq], ['执行中任务', String(data.tasks.length)], ['待恢复记忆', String(data.pending.memory)]].map(([name, value]) => <div className="metric" key={name}><span>{name}</span><strong>{label(value)}</strong></div>)}</div><div className="split overview-split"><section><div className="section-heading"><h2>Agent</h2><Badge value={data.tasks.length ? 'running' : '空闲'} /></div><dl className="facts"><dt>模型</dt><dd>{data.model?.model ?? '未选择'}</dd><dt>提供方</dt><dd>{data.model?.provider ?? '暂无'}</dd><dt>最近交互</dt><dd>{date(data.lastInteraction)}</dd><dt>前台会话</dt><dd className="mono">{data.foregroundSessionId}</dd><dt>待处理出站</dt><dd>{data.pending.outbound}</dd></dl><h3>执行中的任务</h3>{data.tasks.length ? data.tasks.map(task => <div className="record" key={task.sessionId}><b>{task.sessionId.includes('hidden') ? task.sessionId.split('-hidden-')[1] : 'QQ 前台'}</b><span>Turn {task.turn}</span><time>{date(task.startedAt)}</time></div>) : <Empty>当前没有执行中的任务</Empty>}</section><section><div className="section-heading"><h2>下一次唤醒</h2></div>{(['foreground', 'background'] as const).map(role => <div className="wake-row" key={role}><div><b>{label(role)} Heartbeat</b><p>{data.heartbeat.settings[`${role}Paused`] ? '自动唤醒已暂停' : date(data.heartbeat.next[role])}</p></div><span className="frequency">{data.heartbeat.settings[`${role}Ms`] / 60000} min</span></div>)}<div className="section-heading"><h3>最近事件</h3></div>{data.recent.length ? data.recent.slice(-6).reverse().map((item, i) => <div className="record" key={i}><span>{String(item.type)}</span><Badge value={item.status ?? item.actionType} /><time>{date(item.at)}</time></div>) : <Empty />}</section></div></>
}
function Models({ revision, refresh }: { revision: number; refresh: () => void }) {
  const { data, error, loading } = useResource<ModelSettingsView>('model', revision)
  return <><Notice>{error}</Notice>{loading && !data ? <Empty>正在读取模型配置…</Empty> : data ? <ModelEditor key={data.revision} data={data} refresh={refresh} /> : null}</>
}
function ModelEditor({ data, refresh }: { data: ModelSettingsView; refresh: () => void }) {
  const [provider, setProvider] = useState(data.selection.provider); const [model, setModel] = useState(data.selection.model); const [reasoningEffort, setReasoningEffort] = useState(data.selection.reasoningEffort ?? ''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false)
  return <><form className="settings-form model-settings" onSubmit={event => { event.preventDefault(); setBusy(true); setSaved(false); try { const selection = normalizeModelSelection({ provider, model, reasoningEffort }); void api<ModelSettingsView>('model', 'PUT', { selection, expectedRevision: data.revision }).then(() => { setError(''); setSaved(true); refresh() }).catch(error => setError(errorMessage(error))).finally(() => setBusy(false)) } catch (error) { setError(errorMessage(error)); setBusy(false) } }}><div className="section-heading"><div><h2>默认模型</h2><span className="muted">保存后，新请求将使用此模型。</span></div><Badge value={data.applies === 'live' ? '热更新' : '需重启'} /></div><div className="form-grid"><label>提供方<input required maxLength={256} value={provider} onChange={event => { setProvider(event.target.value); setSaved(false) }} placeholder="deepseek-official" /></label><label>模型 ID<input required maxLength={256} value={model} onChange={event => { setModel(event.target.value); setSaved(false) }} placeholder="deepseek-v4.1-flash-expires-on-0910" /></label><label>推理强度（可选）<input maxLength={32} value={reasoningEffort} onChange={event => { setReasoningEffort(event.target.value); setSaved(false) }} placeholder="留空使用提供方默认值" /></label></div><Notice>{error}</Notice><Notice good>{saved ? '配置已写入文件并完成热更新。' : ''}</Notice><div className="actions"><span className="muted">版本 {data.revision}</span><button className="primary" disabled={busy}>{busy ? '正在保存…' : '保存模型配置'}</button></div></form><section><h2>配置文件</h2><dl className="facts"><dt>文件路径</dt><dd className="mono">{data.configPath ?? '由 DSH 运行时管理'}</dd><dt>同步方式</dt><dd>管理页直接写入配置文件，写入成功后再切换运行中的 Agent。</dd><dt>生效边界</dt><dd>已开始的请求继续使用旧模型；保存后的下一条请求使用新模型。</dd><dt>密钥</dt><dd>API Key 只从环境变量或凭据存储读取，不在此页展示或保存。</dd></dl></section></>
}
function Sessions({ revision }: { revision: number }) {
  const { data, error } = useResource<{ items: Array<{ id: string; hidden: boolean; title?: string }> }>('sessions', revision)
  const [hidden, setHidden] = useState(false); const [selected, select] = useState('')
  const items = data?.items.filter(item => hidden || !item.hidden) ?? []
  return <><Notice>{error}</Notice><div className="toolbar"><label className="checkbox"><input type="checkbox" checked={hidden} onChange={event => setHidden(event.target.checked)} />后台会话</label><span className="muted">{items.length} 个会话 · 只读</span></div><div className="split browser-split"><aside className="item-list">{items.map(item => <button key={item.id} className={selected === item.id ? 'selected' : ''} onClick={() => select(item.id)}><b>{item.hidden ? item.id.split('-hidden-')[1] : 'QQ 前台'}</b><small>{item.title ?? item.id}</small></button>)}{!items.length && <Empty>尚无会话</Empty>}</aside><section>{selected ? <SessionReader key={selected} id={selected} revision={revision} /> : <Empty>选择会话</Empty>}</section></div></>
}
function SessionReader({ id, revision }: { id: string; revision: number }) {
  const [events, setEvents] = useState<SessionEvent[]>([]); const [error, setError] = useState(''); const [more, setMore] = useState(false); const [page, nextPage] = useState(0); const cursor = useRef(0)
  useEffect(() => {
    const controller = new AbortController()
    void api<{ events: SessionEvent[]; next: number; hasMore: boolean }>(`session?id=${encodeURIComponent(id)}&from=${cursor.current}`, 'GET', undefined, controller.signal).then(value => { setEvents(previous => mergeEvents(previous, value.events)); cursor.current = value.next; setMore(value.hasMore); setError('') }).catch(error => { if (!controller.signal.aborted) setError(errorMessage(error)) })
    return () => controller.abort()
  }, [id, revision, page])
  return <><div className="section-heading"><h2>{id.includes('hidden') ? id.split('-hidden-')[1] : 'QQ 前台'}</h2><span className="muted">{events.length} 个事件</span></div><Notice>{error}</Notice><div className="messages">{events.map(event => event.type === 'user/message' || event.type === 'assistant/message' ? <article key={event.seq} className={`message ${event.type === 'user/message' ? 'user' : 'assistant'}`}><header><b>{event.type === 'user/message' ? '用户 / 输入' : 'Agent'}</b><time>{date(event.time)}</time><small>#{event.seq}</small></header><div className="prose">{safeMessage(event)}</div></article> : event.type === 'assistant/chunk' ? null : <details key={event.seq} className="event"><summary><span>{event.type}</span><small>#{event.seq} · {date(event.time)}</small></summary><Json value={event.data} /></details>)}</div>{!events.length && <Empty />}{more && <button onClick={() => nextPage(value => value + 1)}>加载更多</button>}</>
}
function Memory({ revision, refresh }: { revision: number; refresh: () => void }) {
  const [q, setQ] = useState(''); const [category, setCategory] = useState(''); const [offset, setOffset] = useState(0); const [tab, setTab] = useState('tree'); const [editing, setEditing] = useState<MemoryDoc | 'new'>(); const [error, setError] = useState('')
  const resource = useResource<{ items: MemoryDoc[]; total: number; profile: string; index: string }>(`memory?q=${encodeURIComponent(q)}&category=${category}&offset=${offset}`, revision)
  const revisions = useResource<{ items: unknown[] }>('memory/revisions', revision)
  return <><div className="tabs">{[['tree', 'Memory Tree'], ['profile', 'PROFILE'], ['index', 'INDEX'], ['revisions', '修订记录']].map(([id, name]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{name}</button>)}</div><Notice>{resource.error || error}</Notice>{tab === 'tree' ? <><div className="toolbar"><input aria-label="搜索记忆" placeholder="搜索长期记忆" value={q} onChange={event => { setQ(event.target.value); setOffset(0) }} /><select aria-label="记忆分类" value={category} onChange={event => { setCategory(event.target.value); setOffset(0) }}><option value="">全部分类</option>{['preferences', 'contexts', 'decisions', 'events', 'archive'].map(value => <option key={value} value={value}>{label(value)}</option>)}</select><button className="primary" onClick={() => setEditing('new')}>新增记忆</button></div><div className="table-wrap"><table><thead><tr><th>记忆</th><th>分类</th><th>重要程度</th><th>更新时间</th><th /></tr></thead><tbody>{resource.data?.items.map(doc => <tr key={doc.path}><td><b>{doc.metadata.summary}</b><small>{doc.path}</small></td><td>{label(doc.metadata.category)}</td><td><Badge value={doc.metadata.importance} /></td><td>{date(doc.metadata.updatedAt)}</td><td><button onClick={() => { void api<MemoryDoc>(`memory/document?path=${encodeURIComponent(doc.path)}`).then(setEditing).catch(error => setError(errorMessage(error))) }}>打开</button></td></tr>)}</tbody></table></div>{!resource.data?.items.length && <Empty /> }<div className="toolbar pagination"><span>{resource.data?.total ?? 0} 条记忆</span><button disabled={!offset} onClick={() => setOffset(value => Math.max(0, value - 100))}>上一页</button><button disabled={offset + 100 >= (resource.data?.total ?? 0)} onClick={() => setOffset(value => value + 100)}>下一页</button></div></> : tab === 'revisions' ? <RecordList items={revisions.data?.items ?? []} /> : <pre className="document">{resource.data?.[tab as 'profile' | 'index'] || '暂无内容'}</pre>}{editing && <MemoryEditor doc={editing} close={() => setEditing(undefined)} saved={() => { setEditing(undefined); refresh() }} />}</>
}
function MemoryEditor({ doc, close, saved }: { doc: MemoryDoc | 'new'; close: () => void; saved: () => void }) {
  const initial = doc === 'new' ? undefined : doc
  const [path, setPath] = useState(initial?.path ?? 'preferences/'); const [summary, setSummary] = useState(initial?.metadata.summary ?? ''); const [content, setContent] = useState(initial?.content ?? ''); const [importance, setImportance] = useState(initial?.metadata.importance ?? 'normal'); const [frequency, setFrequency] = useState(initial?.metadata.frequency ?? 'normal'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const archived = path.startsWith('archive/')
  const submit = async (archive = false) => { setBusy(true); try { await api('memory', 'POST', archive ? { action: 'ARCHIVE', path, expectedHash: initial?.hash } : { action: initial ? 'UPDATE' : 'CREATE', path, summary, content, importance, frequency, ...(initial ? { expectedHash: initial.hash } : {}) }); saved() } catch (error) { setError(errorMessage(error)) } finally { setBusy(false) } }
  return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="记忆编辑"><div className="section-heading"><h2>{initial ? archived ? '归档记忆' : '编辑记忆' : '新增记忆'}</h2><button title="关闭" aria-label="关闭" className="icon-button" onClick={close} disabled={busy}>×</button></div><form onSubmit={event => { event.preventDefault(); void submit() }}><label>路径<input required disabled={!!initial} value={path} maxLength={500} placeholder="preferences/study-time.md" onChange={event => setPath(event.target.value)} /></label><label>摘要<input required readOnly={archived} maxLength={500} value={summary} onChange={event => setSummary(event.target.value)} /></label><div className="form-row">{[['重要程度', importance, setImportance], ['使用频率', frequency, setFrequency]].map(([name, value, setter]) => <label key={String(name)}>{String(name)}<select disabled={archived} value={String(value)} onChange={event => (setter as (v: string) => void)(event.target.value)}>{['low', 'normal', 'high'].map(item => <option key={item} value={item}>{label(item)}</option>)}</select></label>)}</div><label>内容<textarea required readOnly={archived} maxLength={64000} rows={10} value={content} onChange={event => setContent(event.target.value)} /></label>{initial && <small className="muted">来源：{initial.metadata.sources.join(' · ')}</small>}<Notice>{error}</Notice><div className="actions">{initial && !archived && <button type="button" className="danger-text" disabled={busy} onClick={() => { if (window.confirm('归档这条长期记忆？')) void submit(true) }}>归档</button>}<button type="button" onClick={close} disabled={busy}>取消</button>{!archived && <button className="primary" disabled={busy}>{busy ? '保存中…' : '保存记忆'}</button>}</div></form></section></div>
}
function Prompts({ revision, refresh }: { revision: number; refresh: () => void }) {
  const { data, error } = useResource<PromptView>('prompts', revision); const [key, select] = useState('soul')
  return <><div className="tabs">{[['soul', 'SOUL'], ['mission', 'Mission'], ['internal', '后台提示词'], ['history', '版本记录']].map(([id, name]) => <button className={key === id ? 'active' : ''} key={id} onClick={() => select(id)}>{name}</button>)}</div><Notice>{error}</Notice>{data && (key === 'soul' || key === 'mission' ? <PromptEditor key={key} name={key} doc={data[key]} active={data.active} refresh={refresh} /> : key === 'internal' ? Object.entries(data.internal).map(([name, text]) => <section className="document-section" key={name}><h2>{name}<span className="muted"> · 只读</span></h2><pre className="document">{text}</pre></section>) : data.history.slice().reverse().map((entry, i) => <details className="event" key={i}><summary>{entry.key} · {date(entry.at)}<small>{entry.after.hash.slice(0, 12)}</small></summary><Diff before={entry.before.text} after={entry.after.text} /></details>))}</>
}
function PromptEditor({ name, doc, active, refresh }: { name: 'soul' | 'mission'; doc: PromptDoc; active: PromptView['active']; refresh: () => void }) {
  const [baseline, setBaseline] = useState(doc); const [text, setText] = useState(doc.text); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false)
  const changed = text !== baseline.text
  return <form onSubmit={event => { event.preventDefault(); setBusy(true); void api<PromptView>('prompts', 'PUT', { key: name, text, expectedHash: baseline.hash }).then(value => { setBaseline(value[name]); setSaved(true); setError(''); refresh() }).catch(error => setError(errorMessage(error))).finally(() => setBusy(false)) }}><div className="section-heading"><h2>{name === 'soul' ? 'SOUL' : 'Mission'}</h2><span className="mono muted">{doc.hash.slice(0, 12)}</span></div><textarea aria-label="系统提示词内容" className="prompt-editor" required maxLength={64000} value={text} onChange={event => { setText(event.target.value); setSaved(false) }} /><Notice>{error}</Notice><Notice good>{saved ? '已保存，将在下一轮生效。' : ''}</Notice>{doc.hash !== baseline.hash && <Notice>服务器已有更新。刷新后再编辑可避免覆盖冲突。</Notice>}<div className="actions"><span className="muted">{changed ? '有未保存的修改' : '无未保存修改'}</span><button type="button" onClick={() => { setText(doc.text); setBaseline(doc); setError('') }}>重新载入</button><button className="primary" disabled={busy || !changed}>{busy ? '保存中…' : '保存新版本'}</button></div>{changed && <details className="event" open><summary>修改差异</summary><Diff before={baseline.text} after={text} /></details>}<h3>会话使用版本</h3>{Object.entries(active).map(([id, version]) => <div className="record" key={id}><span>{id.includes('hidden') ? id.split('-hidden-')[1] : 'QQ 前台'}</span><code>{version[name === 'soul' ? 'soulHash' : 'missionHash'].slice(0, 12)}</code></div>)}</form>
}
function Diff({ before, after }: { before: string; after: string }) { const rows = promptDifference(before, after); return <div className="diff">{rows.map(row => <div key={row.line}><small>第 {row.line} 行</small><pre className="removed">− {row.before}</pre><pre className="added">+ {row.after}</pre></div>)}{!rows.length && <Empty>没有变化</Empty>}</div> }
function Heartbeat({ revision, refresh }: { revision: number; refresh: () => void }) {
  const { data, error } = useResource<HeartbeatView>('heartbeat', revision); const [runError, setRunError] = useState(''); const [busy, setBusy] = useState(false)
  const run = (role: 'foreground' | 'background') => { if (role === 'foreground' && !window.confirm('运行前台检查？策略允许时可能发送 QQ 消息。')) return; setBusy(true); void api('heartbeat/run', 'POST', { role, requestId: crypto.randomUUID() }).then(() => { refresh(); setRunError('') }).catch(error => setRunError(errorMessage(error))).finally(() => setBusy(false)) }
  return <><Notice>{error || runError}</Notice>{data && <><div className="toolbar"><button disabled={busy || data.jobs.some(job => job.status === 'running' && job.role === 'foreground')} onClick={() => run('foreground')}>运行前台检查（可能发 QQ）</button><button disabled={busy || data.jobs.some(job => job.status === 'running' && job.role === 'background')} onClick={() => run('background')}>运行后台维护</button></div><HeartbeatEditor data={data} refresh={refresh} /><h2>执行记录</h2>{data.jobs.length ? data.jobs.map(job => <div className="record" key={job.id}><b>{label(job.role)}</b><Badge value={job.status} /><span>{job.result?.action?.type ?? job.error ?? '等待结果'}</span><span>{job.result?.policy?.code ? label(job.result.policy.code) : ''}</span><time>{date(job.startedAt)}</time></div>) : <Empty />}</>}</>
}
function HeartbeatEditor({ data, refresh }: { data: HeartbeatView; refresh: () => void }) {
  const [settings, setSettings] = useState(data.settings); const [revision, setRevision] = useState(data.revision); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState(false)
  const policy = settings.policy
  return <form className="settings-form" onSubmit={event => { event.preventDefault(); setBusy(true); void api<HeartbeatView>('heartbeat', 'PUT', { settings, expectedRevision: revision }).then(value => { setSettings(value.settings); setRevision(value.revision); setError(''); setSuccess(true); refresh() }).catch(error => setError(errorMessage(error))).finally(() => setBusy(false)) }}><h2>唤醒与联系策略</h2><div className="form-grid">{(['foreground', 'background'] as const).map(role => <React.Fragment key={role}><label>{label(role)}周期（分钟）<input type="number" required min={1} max={10080} value={settings[`${role}Ms`] / 60000} onChange={event => { setSuccess(false); setSettings({ ...settings, [`${role}Ms`]: Number(event.target.value) * 60000 }) }} /></label><label className="checkbox"><input type="checkbox" checked={settings[`${role}Paused`]} onChange={event => { setSuccess(false); setSettings({ ...settings, [`${role}Paused`]: event.target.checked }) }} />暂停{label(role)}自动唤醒</label></React.Fragment>)}<label>时区<input required value={policy.timeZone} onChange={event => setSettings({ ...settings, policy: { ...policy, timeZone: event.target.value } })} /></label><label>联系冷却（分钟）<input type="number" required min={0} max={10080} value={policy.cooldownMinutes} onChange={event => setSettings({ ...settings, policy: { ...policy, cooldownMinutes: Number(event.target.value) } })} /></label><label>安静时段开始<input type="time" required value={policy.quietHours.start} onChange={event => setSettings({ ...settings, policy: { ...policy, quietHours: { ...policy.quietHours, start: event.target.value } } })} /></label><label>安静时段结束<input type="time" required value={policy.quietHours.end} onChange={event => setSettings({ ...settings, policy: { ...policy, quietHours: { ...policy.quietHours, end: event.target.value } } })} /></label><label>每日联系上限<input type="number" required min={1} max={100} value={policy.maxContactsPerDay} onChange={event => setSettings({ ...settings, policy: { ...policy, maxContactsPerDay: Number(event.target.value) } })} /></label></div><Notice>{error}</Notice><Notice good>{success ? '设置已保存' : ''}</Notice><div className="actions"><button type="button" onClick={() => { setSettings(data.settings); setRevision(data.revision); setError('') }}>重新载入</button><button className="primary" disabled={busy}>保存设置</button></div></form>
}
function Schedules({ revision, refresh }: { revision: number; refresh: () => void }) {
  const { data, error } = useResource<{ items: Array<{ id: string; prompt: string; kind: string; scheduledAt: string; everySeconds?: number; state: string }> }>('schedules', revision)
  const [prompt, setPrompt] = useState(''); const [kind, setKind] = useState('after'); const [amount, setAmount] = useState(30); const [at, setAt] = useState(''); const [failure, setFailure] = useState(''); const [busy, setBusy] = useState(false)
  return <><Notice>{error || failure}</Notice><details className="create-schedule"><summary>新建定时任务</summary><form onSubmit={event => { event.preventDefault(); setBusy(true); const rule = kind === 'at' ? { at: new Date(at).toISOString() } : { [kind === 'after' ? 'after_seconds' : 'every_seconds']: amount * 60 }; void api('schedules', 'POST', { prompt, ...rule }).then(() => { setPrompt(''); setFailure(''); refresh() }).catch(error => setFailure(errorMessage(error))).finally(() => setBusy(false)) }}><label>任务内容<textarea required maxLength={8000} rows={3} value={prompt} onChange={event => setPrompt(event.target.value)} /></label><div className="form-row"><label>触发方式<select value={kind} onChange={event => setKind(event.target.value)}><option value="after">延迟执行一次</option><option value="every">固定周期</option><option value="at">指定本地时间</option></select></label>{kind === 'at' ? <label>执行时间<input type="datetime-local" required value={at} onChange={event => setAt(event.target.value)} /></label> : <label>分钟<input required type="number" min={kind === 'every' ? 5 : 1} max={525600} value={amount} onChange={event => setAmount(Number(event.target.value))} /></label>}</div><div className="actions"><button className="primary" disabled={busy}>创建任务</button></div></form></details><div className="table-wrap"><table><thead><tr><th>任务</th><th>规则</th><th>下次执行</th><th>状态</th><th /></tr></thead><tbody>{data?.items.map(item => <tr key={item.id}><td><div className="prose">{item.prompt}</div><small>{item.id}</small></td><td>{item.kind === 'every' ? `每 ${item.everySeconds! / 60} 分钟` : '一次性'}</td><td>{date(item.scheduledAt)}</td><td>{item.state === 'overdue' ? '已到期' : '待执行'}</td><td><button disabled={busy} className="danger-text" onClick={() => { if (!window.confirm('删除这个定时任务？')) return; setBusy(true); void api('schedules', 'DELETE', { id: item.id }).then(refresh).catch(error => setFailure(errorMessage(error))).finally(() => setBusy(false)) }}>删除</button></td></tr>)}</tbody></table></div>{!data?.items.length && <Empty>暂无定时任务</Empty>}</>
}
function RecordList({ items }: { items: unknown[] }) { return <>{items.length ? items.map((item, index) => { const record = item as Record<string, unknown>; return <details className="event" key={index}><summary><span>{String(record.type ?? record.action ?? record.method ?? '事件')}</span><Badge value={record.status ?? record.result ?? record.actor} /><time>{date(record.at ?? record.time)}</time></summary><Json value={item} /></details> }) : <Empty />}</> }
function Diagnostics({ revision }: { revision: number }) {
  const [type, setType] = useState(''); const [state, setState] = useState(''); const [from, setFrom] = useState('')
  const { data, error } = useResource<{ items: unknown[] }>(`diagnostics?type=${encodeURIComponent(type)}&status=${encodeURIComponent(state)}&from=${from ? encodeURIComponent(new Date(from).toISOString()) : ''}`, revision)
  return <><div className="toolbar"><input aria-label="事件类型" value={type} placeholder="事件类型" onChange={event => setType(event.target.value)} /><select aria-label="执行结果" value={state} onChange={event => setState(event.target.value)}><option value="">全部结果</option>{['completed', 'failure', 'failed', 'pending', 'ok', 'error'].map(value => <option key={value} value={value}>{label(value)}</option>)}</select><input aria-label="起始时间" type="datetime-local" value={from} onChange={event => setFrom(event.target.value)} /></div><Notice>{error}</Notice><RecordList items={data?.items ?? []} /></>
}
function Extensions({ revision }: { revision: number }) {
  const [selected, select] = useState(''); const { data, error } = useResource<{ items: Array<{ path: string; kind: string }>; content?: string }>(`extensions?path=${encodeURIComponent(selected)}`, revision)
  return <><Notice>{error}</Notice><div className="toolbar"><span className="muted">只读 · {data?.items.length ?? 0} 个条目</span></div><div className="split browser-split"><aside className="item-list">{data?.items.map(item => <button className={selected === item.path ? 'selected' : ''} onClick={() => select(item.path)} key={item.path}><b>{item.kind === 'skill' ? 'Skill' : 'Plugin 提案'}</b><small>{item.path}</small></button>)}{!data?.items.length && <Empty />}</aside><section>{selected ? <pre className="document">{data?.content}</pre> : <Empty>选择条目</Empty>}</section></div></>
}
function App() {
  const [authenticated, setAuthenticated] = useState<boolean | undefined>(); const [page, setPage] = useState<Page>('overview'); const [revision, setRevision] = useState(0); const [connected, setConnected] = useState(false); const [menu, setMenu] = useState(false)
  const refresh = useCallback(() => setRevision(value => value + 1), [])
  useEffect(() => { const unauthorized = () => { setAuthenticated(false); setCsrf('') }; window.addEventListener('admin-unauthorized', unauthorized); void api<{ csrfToken: string }>('auth').then(value => { setCsrf(value.csrfToken); setAuthenticated(true) }).catch(() => setAuthenticated(false)); return () => window.removeEventListener('admin-unauthorized', unauthorized) }, [])
  useEffect(() => {
    if (!authenticated) return
    const stream = new EventSource('/api/events'); stream.onopen = () => { setConnected(true); refresh() }; stream.addEventListener('refresh', () => { setConnected(true); refresh() }); stream.onerror = () => { setConnected(false); void api('auth').catch(() => undefined) }
    return () => { stream.close(); setConnected(false) }
  }, [authenticated, refresh])
  if (authenticated === undefined) return <main className="login"><Empty>正在连接本地管理服务…</Empty></main>
  if (!authenticated) return <Login onLogin={() => setAuthenticated(true)} />
  return <div className="app"><aside className={`sidebar ${menu ? 'open' : ''}`}><div className="brand"><span className="brand-symbol">P</span><div>Personal Growth<small>AGENT WORKSPACE</small></div></div><div className="nav-caption">管理工作区</div><nav>{pages.map(([id, title, number]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => { setPage(id); setMenu(false) }}><span>{number}</span>{title}</button>)}</nav><div className="sidebar-bottom"><span className="local-indicator" />本地私有实例<small>127.0.0.1</small><button onClick={() => { void api('logout', 'POST', {}).finally(() => { setAuthenticated(false); setCsrf('') }) }}>退出登录</button></div></aside><div className="main"><header className="topbar"><button className="mobile-menu icon-button" aria-label="导航菜单" onClick={() => setMenu(!menu)}>☰</button><span>Personal Growth Agent <span className="slash">/</span> 管理台</span><div><span className={`connection ${connected ? 'online' : ''}`}>{connected ? '已连接' : '连接中断'}</span><button className="icon-button" title="刷新数据" aria-label="刷新数据" onClick={refresh}>↻</button></div></header><main className="content"><div className="page-heading"><div className="eyebrow">PERSONAL GROWTH / {pages.find(item => item[0] === page)?.[2]}</div><h1>{pages.find(item => item[0] === page)?.[1]}</h1></div>{!connected && <Notice>与 Agent 的连接已中断，以下为最后读取的数据。</Notice>}<Dashboard page={page} revision={revision} refresh={refresh} /></main><footer className="page-footer">PERSONAL GROWTH AGENT<span>PRIVATE · LOCAL</span></footer></div></div>
}
function Dashboard({ page, revision, refresh }: { page: Page; revision: number; refresh: () => void }) {
  const { data, error } = useResource<Status>('status', revision)
  return <><Notice>{error}</Notice>{page === 'overview' ? <Overview data={data} /> : page === 'models' ? <Models revision={revision} refresh={refresh} /> : page === 'sessions' ? <Sessions revision={revision} /> : page === 'memory' ? <Memory revision={revision} refresh={refresh} /> : page === 'prompts' ? <Prompts revision={revision} refresh={refresh} /> : page === 'heartbeat' ? <Heartbeat revision={revision} refresh={refresh} /> : page === 'schedules' ? <Schedules revision={revision} refresh={refresh} /> : page === 'diagnostics' ? <Diagnostics revision={revision} /> : <Extensions revision={revision} />}</>
}
createRoot(document.getElementById('root')!).render(<App />)
